version: "3.8"
services:
  # ----------------------------------------------------------------------------
  # Setup the local redis server.
  #
  redis:
    image: redis:6-alpine
    container_name: ex_commerce_redis_service
    hostname: redis
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--requirepass",
      "${REDIS_PASS}",
      "--save",
      "60",
      "1",
      "--loglevel",
      "warning"
    ]
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'
    networks:
      close:
        aliases:
          - redis

  # ----------------------------------------------------------------------------
  # Setup the local postgres server.
  #
  postgres:
    image: postgres:13
    command: postgres -c 'max_connections=10000'
    container_name: ex_commerce_postgres_service
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    networks:
      close:
        aliases:
          - postgres

  # ----------------------------------------------------------------------------
  # Setup the local postgres server.
  #
  pgadmin:
    container_name: 'ex_commerce_pgadmin_service'
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
        - 5050:80
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin'
    networks:
      close:
        aliases:
          - pgadmin
networks:
  close:
    driver: bridge
volumes:
  redis_data:
  pg_data:
  pgadmin_data:
