name: Code linting CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Code linting
    runs-on: ubuntu-latest
    env:
      # General env
      MIX_ENV: dev
      # Cloudinary env
      CLOUDEX_API_KEY: ${{ secrets.CLOUDEX_API_KEY }}
      CLOUDEX_SECRET: ${{ secrets.CLOUDEX_SECRET }}
      CLOUDEX_CLOUD_NAME: ${{ secrets.CLOUDEX_CLOUD_NAME }}
      # Misc env
      UPLOADS_PATH: "priv/static/uploads/"
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.12.3'
          otp-version: '23.3'
      - name: Output Elixir version
        run: elixir --version
      - name: Output Node.js version
        run: node --version
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Compile app & deps
        run: |
          mix deps.compile
          mix compile
      - name: Setup web client
        run: |
          mix setup.web
      - name: Run formatter
        run: |
          mix check.format
          mix check.credo
